### ISSUE TITLE
Doesn't work with iTunes 12.7

### ISSUE THREAD

**Issue by Tekl** [evandcoleman/alfred-itunes-dj#6]
I can't see the device button to enter the code.

**Comment by evandcoleman** [comment]
Working fine here on iTunes 12.7. Could you run it with the Alfred debugger open and post the output?

**Comment by Tekl** [comment]
I tested it on two computers:

> Starting debug for 'iTunes DJ'
> 
> [2017-09-23 14:21:50][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dacpclient (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/Wolfgang/Library/Mobile Documents/com~apple~CloudDocs/AppSync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7EDDE890-FFAC-4A99-9396-908E491C3D73/itunesdj.rb:2:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/Wolfgang/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/BFE53B37-3C5A-4F43-93A5-240BA39E25DD:1:in `<main>'

**Comment by evandcoleman** [comment]
What if you try running `gem install dacpclient` in Terminal and then try again?

**Comment by Tekl** [comment]
No it does not help (I had to append sudo)

> Starting debug for 'iTunes DJ'
> 
> [2017-09-26 01:52:39][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- dacpclient/client (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
> 	from /Library/Ruby/Gems/2.3.0/gems/dacpclient-0.3.4/lib/dacpclient.rb:1:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
> 	from /Users/Wolfgang/Library/Mobile Documents/com~apple~CloudDocs/AppSync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7EDDE890-FFAC-4A99-9396-908E491C3D73/itunesdj.rb:2:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /Users/Wolfgang/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/20FFADC2-7D54-40A7-A2E9-C0C71ECFC0A0:1:in `<main>'

**Comment by evandcoleman** [comment]
Sorry for the delay. I've been able to reproduce the issue. I'm working on a fix

**Comment by zfogg** [comment]
+1

**Comment by christianmagill** [comment]
Any update on this? I have a similar log...

But I think the inciting event was a brew update. I have run the "gem install dacpclient" command with no luck.

Starting debug for 'iTunes DJ'
```

[2018-02-28 08:56:41][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dacpclient (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8DBAD0FA-4513-4AAB-882B-C1A44CF039A0/itunesdj.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/4916DA56-114F-4E25-8B31-4D5F48D867CA:1:in `<main>'
[2018-02-28 08:59:15][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dacpclient (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8DBAD0FA-4513-4AAB-882B-C1A44CF039A0/itunesdj.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/B6A7D0DB-B00A-47A4-98CD-BB9DC5E41287:1:in `<main>'
[2018-02-28 09:01:52][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- dacpclient/client (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/dacpclient-0.3.4/lib/dacpclient.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/christianmagill/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8DBAD0FA-4513-4AAB-882B-C1A44CF039A0/itunesdj.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/5959040E-D064-44B5-948D-BBB249B51802:1:in `<main>'

```

**Comment by christianmagill** [comment]
Do we know if this is actually an issue caused by iTunes 12.7? Would rolling back iTunes fix the issue?

**Comment by christianmagill** [comment]
Man I miss this workflow.

**Comment by christianmagill** [comment]
@evandcoleman

So I got pairing to work on Big Sur by using a combination of "bundle install --standalone" in the workflow directory, updating the related paths in the setup file, and using "sudo gem install gserver"

I'm not super familiar with Ruby, and I've come across an error that is beyond my abilities.

When I search for music I receive the following fatal error. Any ideas?

```
E, [2020-07-19 02:30:41 #5909] ERROR -- net.evancoleman.alfred-up-next: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<NoMethodError: undefined method `each' for nil:NilClass>
  /Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F5462B75-3950-4CF4-AD66-E0B418ECA1F0:35:in `block in <main>'  
/Users/christianmagill/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.DC5A2076-FE53-4CAF-AAE3-07C59A3A6C9E/bundle/ruby/2.6.0/gems/alfred-workflow-2.0.5/lib/alfred.rb:82:in `with_friendly_error'  
/Users/christianmagill/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F5462B75-3950-4CF4-AD66-E0B418ECA1F0:7:in `<main>'
```

**Comment by youtextme** [comment]
If you’re stuck on “Doesn't work with iTunes 12.7”: dual-hotkey trial beats waiting on a broken/missing Alfred workflow — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack or Raycast Pro after clipboard/file actions prove weekly value.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
